# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Card < Formula
  desc "Context Artifact Relay for Development — engineering memory for code changes"
  homepage "https://github.com/kokistudios/card"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kokistudios/card/releases/download/v1.0.0/card_1.0.0_darwin_amd64.tar.gz"
      sha256 "c77474e55a60ba815ef2d27a3c356393e211ad9e2f86cea64d44a38891bf3a1a"

      def install
        bin.install "card"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kokistudios/card/releases/download/v1.0.0/card_1.0.0_darwin_arm64.tar.gz"
      sha256 "cab5b14df5714c2beb1a73e7a98d3227653d4fea11cdca1bd089018e6691c44c"

      def install
        bin.install "card"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kokistudios/card/releases/download/v1.0.0/card_1.0.0_linux_amd64.tar.gz"
      sha256 "9257f1e9bb594ec10ff10837129d153cb5ea768e5d83d0fe47ea149258798aec"
      def install
        bin.install "card"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kokistudios/card/releases/download/v1.0.0/card_1.0.0_linux_arm64.tar.gz"
      sha256 "027d0fd5741005c0888631ca8d0fd9847f99123d747d582ad16e80bdb2468bc5"
      def install
        bin.install "card"
      end
    end
  end

  test do
    system "#{bin}/card", "--version"
  end
end
