# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Card < Formula
  desc "Context Artifact Relay for Development — engineering memory for code changes"
  homepage "https://github.com/kokistudios/card"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kokistudios/card/releases/download/v1.0.0/card_1.0.0_darwin_amd64.tar.gz"
      sha256 "87c313f73a2224c7eeaa366bcc788c11f1e6638a5010e9f6cb1c63eb3da7d710"

      def install
        bin.install "card"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kokistudios/card/releases/download/v1.0.0/card_1.0.0_darwin_arm64.tar.gz"
      sha256 "b1937c3e6971aea0218d725dee994c776213ffcd65147f898766a73686a98d19"

      def install
        bin.install "card"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kokistudios/card/releases/download/v1.0.0/card_1.0.0_linux_amd64.tar.gz"
      sha256 "f8d89c77fbca98e070ca85e5f7ecb7230582e12b2610e56a978585c476bfa7ff"
      def install
        bin.install "card"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kokistudios/card/releases/download/v1.0.0/card_1.0.0_linux_arm64.tar.gz"
      sha256 "e7100d0a467395db8e47876fe6178ad84c757150ea0dccc6ed18950927d06bf8"
      def install
        bin.install "card"
      end
    end
  end

  test do
    system "#{bin}/card", "--version"
  end
end
